<?php

namespace AddressBook\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithSociete($id) {
        // HEREDOC
        $dql = <<<DQL
SELECT c, s
FROM AddressBook\Entity\Contact c
LEFT JOIN c.societe s
WHERE c.id = :id
DQL;

        $query = $this->_em->createQuery($dql);
        $query->setParameter('id', $id);

        return $query->getSingleResult();
    }
}
