<?php $this->headTitle('Liste des contacts'); ?>

<h2>Liste des contacts</h2>

<?php echo $this->bootstrapFlashMessenger(); ?>

<table class="table table-striped table-bordered">
    <tr>
        <th>Nom complet</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($contacts as $c) : ?>
    <tr>
        <td><?php echo $this->escapeHtml($c->getPrenom()); ?> <?php echo $this->escapeHtml($c->getNom()); ?></td>
        <td>
            <a class="btn btn-xs btn-primary" href="<?php echo $this->url('contact/show', array('id' => $c->getId())); ?>">Afficher</a>
            <a class="btn btn-xs btn-warning" href="<?php echo $this->url('contact/show/modify', array('id' => $c->getId())); ?>">Modifier</a>
            <a class="btn btn-xs btn-danger" href="<?php echo $this->url('contact/show/delete', array('id' => $c->getId())); ?>">Supprimer</a>
        </td>
    </tr>
    <?php endforeach; ?>
</table>


<?php //$this->inlineScript()->captureStart(); ?>
<!--var p = document.querySelector('p');-->
<!---->
<!--setInterval(function() {-->
<!--    p.classList.toggle('off');-->
<!--}, 1000);-->
<?php //$this->inlineScript()->captureEnd(); ?>
<!---->
<?php //$this->headStyle()->captureStart(); ?>
<!--.navbar-default {-->
<!--    background-color: yellow;-->
<!--}-->
<!--p.off {-->
<!--    display: none;-->
<!--}-->
<?php //$this->headStyle()->captureEnd(); ?>
