<?php $this->headTitle('Liste des contacts'); ?>

<h2>Liste des contacts</h2>

<table class="table table-striped table-bordered">
    <tr>
        <th>Nom complet</th>
        <th>Actions</th>
    </tr>
    <tr>
        <td>Jean Dupont</td>
        <td>
            <a class="btn btn-xs btn-primary" href="/contacts/1">Afficher</a>
            <a class="btn btn-xs btn-warning" href="/contacts/1/modify">Modifier</a>
            <a class="btn btn-xs btn-danger" href="/contacts/1/delete">Supprimer</a>
        </td>
    </tr>
    <tr>
        <td>Eric Martin</td>
        <td>
            <a class="btn btn-xs btn-primary" href="/contacts/2">Afficher</a>
            <a class="btn btn-xs btn-warning" href="/contacts/2/modify">Modifier</a>
            <a class="btn btn-xs btn-danger" href="/contacts/2/delete">Supprimer</a>
        </td>
    </tr>
</table>


<?php //$this->inlineScript()->captureStart(); ?>
<!--var p = document.querySelector('p');-->
<!---->
<!--setInterval(function() {-->
<!--    p.classList.toggle('off');-->
<!--}, 1000);-->
<?php //$this->inlineScript()->captureEnd(); ?>
<!---->
<?php //$this->headStyle()->captureStart(); ?>
<!--.navbar-default {-->
<!--    background-color: yellow;-->
<!--}-->
<!--p.off {-->
<!--    display: none;-->
<!--}-->
<?php //$this->headStyle()->captureEnd(); ?>
